apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: logflow
data:
  PORT: "3003"
  SERVICE_NAME: "worker"
  WORK_INTERVAL_MS: "4000"
  LOG_COLLECTOR_URL: "http://dashboard.logflow.svc.cluster.local:3000"
