apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: logflow
  labels:
    app: worker
    app.kubernetes.io/part-of: logflow
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - name: http
      port: 3003
      targetPort: 3003
