apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: logflow
  labels:
    app: payments-api
    app.kubernetes.io/part-of: logflow
spec:
  type: ClusterIP
  selector:
    app: payments-api
  ports:
    - name: http
      port: 3001
      targetPort: 3001
