apiVersion: v1
kind: ConfigMap
metadata:
  name: web-api-config
  namespace: logflow
data:
  PORT: "3002"
  SERVICE_NAME: "web-api"
  LOG_COLLECTOR_URL: "http://dashboard.logflow.svc.cluster.local:3000"
