apiVersion: v1
kind: Service
metadata:
  name: web-api
  namespace: logflow
  labels:
    app: web-api
    app.kubernetes.io/part-of: logflow
spec:
  type: ClusterIP
  selector:
    app: web-api
  ports:
    - name: http
      port: 3002
      targetPort: 3002
